const assert=require('node:assert/strict');
const fs=require('node:fs');
global.window=global;
global.document={readyState:'loading',addEventListener(){},getElementById(){return null},querySelector(){return null},body:{appendChild(){}}};
require('../app-v84/www/admin-users-v1.js');
assert.equal(global.LariosAdminUsers.__test.roleLabel('admin'),'Administrador');
assert.equal(global.LariosAdminUsers.__test.roleLabel('employee'),'Empleado');
assert.equal(global.LariosAdminUsers.__test.roleLabel('none'),'Sin acceso');
const ui=fs.readFileSync(require.resolve('../app-v84/www/admin-users-v1.js'),'utf8');
assert.match(ui,/Usuarios y permisos/);
assert.match(ui,/data-admin-only/);
assert.match(ui,/functions\/v1\/admin-users/);
assert.match(ui,/Tu cuenta administradora/);
assert.match(ui,/Añadir usuario/);
assert.match(ui,/Restablecer contraseña/);
assert.match(ui,/Eliminar usuario/);
const edge=fs.readFileSync(require.resolve('../supabase/functions/admin-users/index.ts'),'utf8');
assert.match(edge,/app_metadata\?\.role !== "admin"/);
assert.match(edge,/CANNOT_CHANGE_OWN_ROLE/);
assert.match(edge,/LAST_ADMIN/);
assert.match(edge,/auth\.admin\.listUsers/);
assert.match(edge,/auth\.admin\.updateUserById/);
assert.match(edge,/auth\.admin\.inviteUserByEmail/);
assert.match(edge,/resetPasswordForEmail/);
assert.match(edge,/auth\.admin\.deleteUser/);
assert.doesNotMatch(edge,/user_metadata/);
console.log('admin user management: ok');
