const assert=require('node:assert/strict');
const fs=require('node:fs');
global.window=global;
global.document={readyState:'loading',addEventListener(){},createElement(){return{className:'',dataset:{},appendChild(){},set textContent(v){this._text=v},set innerHTML(v){this._html=v}}},head:{appendChild(){}}};
require('../app-v84/www/contract-lifecycle-v6.js');
const t=global.LariosLifecycle.__test;
const rate={category:'Grupo A',pricing_type:'fixed_days',day_1:78,day_2:137,day_3:190,day_4:240,day_5:285,day_6:325,day_7:360,extra_day:45,insurance_first_day:20,insurance_extra_day:10,season_94_markup:20};
t.setPricing([rate]);
assert.equal(t.baseRental(rate,1),78);
assert.equal(t.baseRental(rate,2),137);
const simple=t.extensionCalculation({vehicle_group:'A',vehicle_quantity:1,rental_days:1,total:78,discount_percent:0,full_insurance:false,young_driver:false},1);
assert.equal(simple.baseDelta,59);
assert.equal(simple.amount,59);
assert.equal(simple.total,137);
const full=t.extensionCalculation({vehicle_group:'A',vehicle_quantity:1,rental_days:1,total:113,discount_percent:10,full_insurance:true,young_driver:true,extras_detail:[{key:'child_seat',qty:1}]},1);
assert.equal(full.baseDelta,59);
assert.equal(full.discountDelta,5.9);
assert.equal(full.insuranceDelta,10);
assert.equal(full.youngDelta,5);
assert.equal(full.extrasDelta,6);
assert.equal(full.amount,74.1);
const discounted=t.calculateTotal({rent:100,insuranceTotal:20,youngTotal:5,extrasTotal:10,discountPercent:10});
assert.equal(discounted.discount,10);
assert.equal(discounted.total,125);
const groupB={category:'Grupo B',pricing_type:'fixed_days',day_1:87,day_2:157,insurance_first_day:15,insurance_extra_day:5};
t.setPricing([groupB]);
const lr062642=t.extensionCalculation({vehicle_group:'B',vehicle_quantity:1,rental_days:1,total:87,discount_percent:0,full_insurance:false,young_driver:false},1);
assert.equal(lr062642.amount,70);
assert.equal(lr062642.total,157);
const start=new Date('2026-09-01T10:00:00');
assert.equal(t.extensionDaysBetween(start,new Date('2026-09-02T13:00:00')),1);
assert.equal(t.extensionDaysBetween(start,new Date('2026-09-02T13:01:00')),2);
t.setPricing([rate]);
const seasonal=t.extensionCalculation({vehicle_group:'A',vehicle_quantity:1,rental_days:1,total:93.6,discount_percent:0,full_insurance:false,young_driver:false,tariff94:true,tariff_markup_percent:20},1);
assert.ok(Math.abs(seasonal.baseDelta-70.8)<0.001);
const lifecycleSource=fs.readFileSync(require.resolve('../app-v84/www/contract-lifecycle-v6.js'),'utf8');
assert.match(lifecycleSource,/generateBtn\.addEventListener\('pointerup',activate/);
assert.match(lifecycleSource,/generateBtn\.addEventListener\('touchend',activate/);
assert.match(lifecycleSource,/generateBtn\.addEventListener\('click',activate/);
assert.match(lifecycleSource,/Listo para generar · AMPLIACIONES V6/);
assert.match(lifecycleSource,/try\{await refreshAgenda\(\)\}catch\(e\)\{console\.warn\('La ampliación terminó/);
assert.equal(typeof global.LariosLifecycle.generateExtension,'function');
console.log('contract lifecycle calculations: ok');
