const assert=require('node:assert/strict');
const fs=require('node:fs');
global.window=global;global.document={readyState:'loading',addEventListener(){},createElement(){return{}},body:{appendChild(){}},head:{appendChild(){}}};
require('../app-v84/www/contract-panel-v1.js');
const t=global.LariosContractPanel.__test;
t.setData([{renthub_sync_status:'verified'}],{configured:false});
assert.deepEqual(t.state({renthub_sync_status:'verified'}),['Verificado','ok']);
assert.deepEqual(t.state({status:'confirmed',renthub_sync_status:'pending'}),['Pendiente de activar','wait']);
const source=fs.readFileSync(require.resolve('../app-v84/www/contract-panel-v1.js'),'utf8');
assert.match(source,/Panel contractual/);
assert.match(source,/Caché Renthub/);
assert.match(source,/Sin datos personales/);
assert.match(source,/refresh_cache/);
assert.match(source,/Eliminar copia local/);
const edge=fs.readFileSync(require.resolve('../supabase/functions/renthub-transfer/index.ts'),'utf8');
assert.match(edge,/contains_personal_data: false/);
assert.match(edge,/action === "refresh_cache"/);
assert.match(edge,/config\/locations/);
console.log('contract panel and Renthub cache: ok');
