const assert=require('node:assert/strict');
const fs=require('node:fs');
global.window=global;
global.document={readyState:'loading',addEventListener(){},createElement(){return{appendChild(){},set textContent(v){this._text=v}}},head:{appendChild(){}}};
require('../app-v84/www/renthub-manual-v1.js');
const t=global.LariosRenthub.__test;
t.setContracts([{id:'1',contract_number:'LR-062700',status:'confirmed'}]);
assert.equal(t.byNumber('LR-062700').id,'1');
assert.equal(t.byNumber('62700').id,'1');
const source=fs.readFileSync(require.resolve('../app-v84/www/renthub-manual-v1.js'),'utf8');
assert.match(source,/Mandar datos Renthub · pendiente de activar/);
assert.match(source,/Eliminar copia local/);
assert.match(source,/pendiente de verificar PDF/);
assert.match(source,/se volverá a comprobar/);
assert.match(source,/Esta acción no se puede deshacer/);
const edge=fs.readFileSync(require.resolve('../supabase/functions/renthub-transfer/index.ts'),'utf8');
assert.match(edge,/send_confirmation_email", "0"/);
assert.match(edge,/booking\/details/);
assert.match(edge,/api\/v1\/upload\/rental_reservation/);
assert.match(edge,/RENTHUB_PURGE_ENABLED/);
assert.match(edge,/renthub_sync_status: "verified"/);
assert.match(edge,/app_purge_verified_renthub_contract/);
console.log('manual Renthub handoff: ok');
