const assert=require('node:assert/strict');
const fs=require('node:fs');
global.window=global;
global.document={readyState:'loading',addEventListener(){},getElementById(){return null},querySelector(){return null},createElement(){return{}},head:{appendChild(){}}};
require('../app-v84/www/reservation-admin-v1.js');
assert.equal(typeof global.LariosAdminReservations.remove,'function');
const ui=fs.readFileSync(require.resolve('../app-v84/www/reservation-admin-v1.js'),'utf8');
assert.match(ui,/Guardar cambios/);
assert.match(ui,/continuar más tarde/);
assert.match(ui,/Eliminar reserva cancelada/);
assert.match(ui,/functions\/v1\/admin-contracts/);
assert.match(ui,/Última confirmación/);
const edge=fs.readFileSync(require.resolve('../supabase/functions/admin-contracts/index.ts'),'utf8');
assert.match(edge,/app_metadata\?\.role !== "admin"/);
assert.match(edge,/RENTHUB_COPY_EXISTS/);
assert.match(edge,/PAYMENT_EXISTS/);
assert.match(edge,/delete_cancelled_local_reservation/);
assert.match(edge,/storage\.from\("contracts"\)\.remove/);
assert.match(edge,/storage\.from\("documents"\)\.remove/);
console.log('reservation draft and cancellation controls: ok');
