const assert=require('node:assert/strict');
const fs=require('node:fs');
global.window=global;
global.document={readyState:'loading',addEventListener(){},getElementById(){return null},querySelector(){return null},querySelectorAll(){return[]},body:{classList:{toggle(){}},appendChild(){}}};
global.alert=()=>{};
require('../app-v84/www/role-access-v1.js');
const access=global.LariosAccess;
access.__test.setRole('employee');
assert.equal(access.isEmployee(),true);
assert.equal(access.isAdmin(),false);
assert.equal(access.__test.label(),'Empleado');
access.__test.setRole('admin');
assert.equal(access.isAdmin(),true);
assert.equal(access.__test.label(),'Administrador');
const ui=fs.readFileSync(require.resolve('../app-v84/www/role-access-v1.js'),'utf8');
assert.match(ui,/Campos editables por empleados/);
assert.match(ui,/Solo administrador/);
assert.match(ui,/app_metadata/);
assert.match(ui,/if\(!isAdmin\(\)\)button\.disabled=true/);
assert.doesNotMatch(ui,/button\.disabled=!isAdmin/);
assert.match(ui,/__lariosRoleSessionHook/);
assert.match(ui,/markVersion/);
const panel=fs.readFileSync(require.resolve('../app-v84/www/contract-panel-v1.js'),'utf8');
assert.match(panel,/data-admin-only="true"/);
assert.match(panel,/requireAdmin\('enviar los contratos pendientes a Renthub'\)/);
const edge=fs.readFileSync(require.resolve('../supabase/functions/renthub-transfer/index.ts'),'utf8');
assert.match(edge,/role !== "admin"/);
assert.match(edge,/ADMIN_REQUIRED/);
const migration=fs.readFileSync(require.resolve('../supabase/migrations/20260829130000_employee_admin_permissions.sql'),'utf8');
assert.match(migration,/employees update draft contracts/);
assert.match(migration,/admins delete contracts/);
assert.match(migration,/staff read pricing/);
assert.match(migration,/staff read renthub sync log/);
const hardening=fs.readFileSync(require.resolve('../supabase/migrations/20260829133000_permissions_advisor_hardening.sql'),'utf8');
assert.match(hardening,/revoke all on function public\.notify_contract_email\(\)/);
assert.match(hardening,/create policy "staff update contracts"/);
console.log('employee/admin access controls: ok');
