const assert=require('node:assert/strict');
const fs=require('node:fs');
global.window=global;
global.document={readyState:'loading',addEventListener(){}};
require('../app-v84/www/vehicle-manager-v1.js');
const t=global.LariosVehicleManager.__test;
assert.equal(t.plate(' 1234-abc '),'1234ABC');
const source=fs.readFileSync(require.resolve('../app-v84/www/vehicle-manager-v1.js'),'utf8');
assert.doesNotMatch(source,/lrVmCategory|assigned_vehicle_group|bindReservation|setInterval|datalist/);
assert.match(source,/select=id,registration,make,model,fuel_type/);
assert.match(source,/Catálogo independiente por matrícula/);
const core=fs.readFileSync(require.resolve('../app-v84/www/vehicle-core-v1.js'),'utf8');
assert.doesNotMatch(core,/lrCoreBlocker|createElement\(['"]select['"]\)/);
const fixes=fs.readFileSync(require.resolve('../app-v84/www/larios-fixes.js'),'utf8');
const legacyPatch=fixes.match(/function patchVehicleSelector\(\)\{[^}]+\}/)?.[0]||'';
assert.match(legacyPatch,/remove\(\)/);
assert.doesNotMatch(legacyPatch,/createElement|category|filter/);
console.log('vehicle manager helpers: ok');
